# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: colinmerkel/mushu-ci:latest

    working_directory: /go/src/github.com/colin353/mushu-new
    steps:
      - checkout

        # Run go tests.
      - run: cd server; go get -v -t -d ./...
      - run: cd server; go test -v ./...

        # Try to build the elm code.
      - run: cd js; sysconfcpus -n 2 elm make --yes Main.elm
      - run: cd js; sysconfcpus -n 2 elm-test

  deploy:
    docker:
      # specify the version
      - image: colinmerkel/mushu-ci:latest

    working_directory: /go/src/github.com/colin353/mushu-new
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: sysconfcpus -n 2 ./build.sh --release
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t colinmerkel/mushu .
      - run: docker push colinmerkel/mushu
        # Update the server's docker image.
      - run: echo $GCP_TOKEN | base64 --decode --ignore-garbage > ${HOME}/gcloud-key.json
      - run: ~/google-cloud-sdk/bin/gcloud -q auth activate-service-account --key-file=${HOME}/gcloud-key.json
      - run: ~/google-cloud-sdk/bin/gcloud -q config set project mushu-194218
      - run: ~/google-cloud-sdk/bin/gcloud -q compute ssh --zone=us-east1-b colin@instance-1 -- 'docker pull docker.io/colinmerkel/mushu; docker stop instance-1; docker rm instance-1; docker run -d --name=instance-1 --restart=always -p 80:80 docker.io/colinmerkel/mushu'
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
