# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: colinmerkel/mushu-ci:latest
      
    working_directory: /go/src/github.com/colin353/mushu-new
    steps:
      - checkout

        # Run go tests.
      - run: cd server; go get -v -t -d ./...
      - run: cd server; go test -v ./...

        # Try to build the elm code.
      - run: npm install -g elm
      - run: cd js; elm make Main.elm
